### ISSUE TITLE
The humongous todo list

### ISSUE THREAD

**Issue by Lykrast** [Lykrast/UniversalBestiary#1]
Not even sure I'll even do the whole list. Surely missed a lot of cool stuff, surely put a lot of stuff that no one uses. The ordering is mostly arbitrary.

Mods listed here with a check have at least been accepted into the mod. They are either fully or partially implemented. 

**Seen in a recent popular modpack**
- [ ] [Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution) (entities registered too late, issue opened)
- [ ] [Forestry](https://minecraft.curseforge.com/projects/forestry) (entities registered too late)
- [ ] [The Twilight Forest](https://minecraft.curseforge.com/projects/the-twilight-forest)
- [x] [Thaumcraft](https://minecraft.curseforge.com/projects/thaumcraft)
- [ ] [PneumaticCraft: Repressurized](https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized)
- [ ] [Roots 3](https://minecraft.curseforge.com/projects/roots)
- [x] [Embers Rekindled](https://www.curseforge.com/minecraft/mc-mods/embers-rekindled)
- [x] [Wizardry Mod](https://minecraft.curseforge.com/projects/wizardry-mod)
- [ ] [Minecolonies](https://minecraft.curseforge.com/projects/minecolonies)
- [x] [The Betweenlands](https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod)
- [ ] [AbyssalCraft](https://minecraft.curseforge.com/projects/abyssalcraft)
- [x] [Random Things](https://minecraft.curseforge.com/projects/random-things)
- [ ] [EvilCraft](https://minecraft.curseforge.com/projects/evilcraft)
- [ ] [Animania](https://minecraft.curseforge.com/projects/animania)
- [ ] [Chickens](https://minecraft.curseforge.com/projects/chickens)
- [ ] [More Chickens](https://minecraft.curseforge.com/projects/more-chickens)
- [ ] [Hatchery](https://minecraft.curseforge.com/projects/hatchery)
- [ ] [Ducky Mod](https://minecraft.curseforge.com/projects/ducky-mod)
- [ ] [Enderman Evolution](https://minecraft.curseforge.com/projects/enderman-evolution)
- [ ] [MobTotems](https://minecraft.curseforge.com/projects/mobtotems)

**Requested and not above**
- [ ] [Grim Pack](https://minecraft.curseforge.com/projects/grim-pack)
- [ ] [Gravestone mod - Extended](https://minecraft.curseforge.com/projects/gravestone-mod-extended)
- [x] [Grimoire of Gaia](https://minecraft.curseforge.com/projects/grimoire-of-gaia)
- [ ] [EmberRoot Zoo](https://minecraft.curseforge.com/projects/emberroot-zoo)
- [ ] [Ender IO Zoo](https://minecraft.curseforge.com/projects/ender-io-zoo)
- [x] [Aether Legacy](https://minecraft.curseforge.com/projects/aether-legacy)
- [x] [The Aether II](https://minecraft.curseforge.com/projects/the-aether-ii)
- [ ] [Mo' Creatures](https://minecraft.curseforge.com/projects/mo-creatures)
- [x] [Mowzie's Mobs](https://minecraft.curseforge.com/projects/mowzies-mobs)
- [x] [NetherEx](https://minecraft.curseforge.com/projects/netherex)
- [ ] [Deadly Monsters](https://minecraft.curseforge.com/projects/deadly-monsters)
- [ ] [Dungeon Mobs Reborn](https://minecraft.curseforge.com/projects/dungeon-mobs-reborn)
- [ ] [Eerie Entities](https://minecraft.curseforge.com/projects/eerie-entities)
- [ ] [Familiar Fauna](https://minecraft.curseforge.com/projects/familiar-fauna)
- [ ] [The Summoner](https://minecraft.curseforge.com/projects/the-summoner)
- [ ] [killagers](https://minecraft.curseforge.com/projects/killager-mod)
- [x] ~~[The Midnight](https://minecraft.curseforge.com/projects/the-midnight)~~ (wait for 1.0)
- [ ] [PrimalCore](https://minecraft.curseforge.com/projects/primalcore)
- [ ] [Zoo & Wild Animals Rebuilt](https://minecraft.curseforge.com/projects/zoo-wild-animals-rebuild)
- [ ] [Lil' Critters](https://minecraft.curseforge.com/projects/lil-critters) (Zoo & Wild Animals Rebuilt addon)
- [ ] [Natural Fauna Mod](https://minecraft.curseforge.com/projects/natural-fauna-mod-a-zawa-addon) (Zoo & Wild Animals Rebuilt addon)
- [ ] [Zoocraft Discoveries](https://minecraft.curseforge.com/projects/zoocraft-discoveries)
- [ ] [Mob Mash](https://minecraft.curseforge.com/projects/mob-mash)
- [ ] [JurassiCraft](https://minecraft.curseforge.com/projects/jurassicraft)
- [ ] [Abyss: Voice](https://minecraft.curseforge.com/projects/abyss-voice)
- [ ] [End: Reborn](https://minecraft.curseforge.com/projects/end-reborn)
- [ ] [Corvus](https://minecraft.curseforge.com/projects/corvus)
- [ ] [Cannibalism](https://minecraft.curseforge.com/projects/cannibalism)
- [ ] [Coherent Villages](https://minecraft.curseforge.com/projects/coherent-villages)
- [ ] [Historicized Medicine](https://minecraft.curseforge.com/projects/historicized-medicine)
- [ ] [Animalium](https://minecraft.curseforge.com/projects/animalium)
- [ ] [Story of Life](https://minecraft.curseforge.com/projects/story-of-life)
- [ ] [Creature Whisperer](https://minecraft.curseforge.com/projects/creature-whisperer)
- [ ] [The Fauna Amplification](https://minecraft.curseforge.com/projects/tfa)
- [ ] [Atum 2: Return to the Sands](https://minecraft.curseforge.com/projects/atum)
- [ ] [The Frozen Lands](https://minecraft.curseforge.com/projects/the-frozen-lands)

**Author offered help**
- [x] [Better Animals Plus](https://minecraft.curseforge.com/projects/betteranimalsplus)
- [x] [Primitive Mobs](https://minecraft.curseforge.com/projects/primitive-mobs)
- [ ] [Exotic Birds](https://minecraft.curseforge.com/projects/exotic-birds)

**Not in anything above, probably unsorted**
- [ ] [Lycanites Mobs](https://minecraft.curseforge.com/projects/lycanites-mobs)
- [ ] [Galacticraft](https://micdoodle8.com/mods/galacticraft)
- [x] [Electroblob's Wizardry](https://minecraft.curseforge.com/projects/electroblobs-wizardry)
- [ ] [Techguns](https://minecraft.curseforge.com/projects/techguns)
- [x] [The Erebus](https://minecraft.curseforge.com/projects/the-erebus)
- [ ] [Waddles](https://minecraft.curseforge.com/projects/waddles)
- [ ] [The Beneath](https://minecraft.curseforge.com/projects/the-beneath)
- [x] [Magma Monsters](https://minecraft.curseforge.com/projects/magma-monsters)
- [ ] [Spectrite](https://minecraft.curseforge.com/projects/spectrite-mod)
- [ ] [Elemental Creepers Redux](https://minecraft.curseforge.com/projects/elemental-creepers-redux)
- [ ] [Project: Vibrant Journeys](https://minecraft.curseforge.com/projects/project-vibrant-journeys)
- [ ] [Grue](https://minecraft.curseforge.com/projects/grue)
- [ ] [Candy World](https://minecraft.curseforge.com/projects/candy-world)
- [ ] [Better With Mods](https://minecraft.curseforge.com/projects/better-with-mods)
- [ ] [Better With Addons](https://minecraft.curseforge.com/projects/better-with-addons)
- [ ] [Laser Creeper Robot Dino Riders From Space](https://minecraft.curseforge.com/projects/laser-creeper-robot-dino-riders-from-space)
- [ ] [ChocoCraft 3](https://minecraft.curseforge.com/projects/chococraft-3)
- [ ] [Reptile Mod](https://minecraft.curseforge.com/projects/reptilemod)
- [ ] [Defiled Lands](https://minecraft.curseforge.com/projects/defiled-lands)
- [x] [Mystic World](https://minecraft.curseforge.com/projects/mystic-world)
- [ ] [Hated Mobs](https://minecraft.curseforge.com/projects/hated-mobs)
- [ ] [SpookyCraft](https://minecraft.curseforge.com/projects/spookycraft)
- [ ] [Tartheus](https://minecraft.curseforge.com/projects/tartheus)
- [ ] [Rocket Squids](https://minecraft.curseforge.com/projects/rocket-squids)
- [ ] [Shadowrite](https://minecraft.curseforge.com/projects/shadowrite)
- [ ] [Millénaire](https://minecraft.curseforge.com/projects/millenaire)
- [x] [Totemic](https://minecraft.curseforge.com/projects/totemic)
- [ ] [Lizard Doggo](https://minecraft.curseforge.com/projects/sbm-lizard-dogo)
- [ ] [Worlds Retold](https://minecraft.curseforge.com/projects/worlds-retold)
- [ ] [Roots Classic](https://minecraft.curseforge.com/projects/roots-classic)
- [ ] [Red Mobs](https://minecraft.curseforge.com/projects/redstone-mobs)
- [ ] [Voidaic Arcania](https://minecraft.curseforge.com/projects/voidaic-arcania)
- [ ] [Cavern II](https://minecraft.curseforge.com/projects/cavern2)
- [ ] [Dungeon Tactics](https://minecraft.curseforge.com/projects/dungeon-tactics)
- [ ] [Pyramid Plunder](https://minecraft.curseforge.com/projects/pyramid-plunder)
- [ ] [Tropicraft](https://minecraft.curseforge.com/projects/tropicraft)
- [x] [Straw Golem](https://minecraft.curseforge.com/projects/strawgolem)
- [ ] [Moolands](https://minecraft.curseforge.com/projects/moolands)
