### ISSUE TITLE
Twilight Forest checklist

### ISSUE THREAD

**Issue by Lykrast** [Lykrast/UniversalBestiary#7]
Monsters:

- [ ] Armored Giant
- [ ] Block and Chain Goblin
- [ ] Death Tome
- [x] Fire Beetle
- [ ] Giant Miner
- [ ] Lower Goblin Knight
- [ ] Upper Goblin Knight
- [x] Hedge Spider
- [ ] Helmet Crab
- [x] Hostile Wolf
- [ ] King Spider
- [x] Kobold
- [ ] Lich Minion
- [ ] Maze Slime
- [ ] Carminite Ghastling
- [ ] Minotaur
- [ ] Mist Wolf
- [ ] Mosquito Swarm
- [x] Pinch Beetle
- [x] Redcap Goblin
- [x] Redcap Sapper
- [ ] Skeleton Druid
- [x] Slime Beetle
- [ ] Snow Guardian
- [ ] Stable Ice Core
- [x] Swarm Spider
- [ ] Carminite Broodling
- [ ] Carminite Ghastguard
- [ ] Carminite Golem
- [ ] Towerwood Borer
- [ ] Cave Troll
- [ ] Unstable Ice Core
- [ ] Winter Wolf
- [x] Twilight Wraith
- [ ] Yeti

Helpers:

- [ ] Loyal Zombie

Bosses:

- [ ] Hydra
- [ ] Knight Phantom
- [ ] Twilight Lich
- [ ] Minoshroom
- [ ] Naga
- [ ] Questing Ram
- [ ] Snow Queen
- [ ] Ur-Ghast
- [ ] Alpha Yeti
